### ISSUE TITLE
Design & Layout Adpations 

### ISSUE THREAD

**Issue by NChristina** [VALIDproject/netflower#140]
header, footer, filter area

**Comment by NChristina** [comment]
![bildschirmfoto 2018-02-12 um 16 08 07](https://user-images.githubusercontent.com/18003747/36103134-c90b0302-100e-11e8-9d57-d54a5de9af71.png)
I am not sure if the "Start Visualization" Button is ok in this position??

**Comment by alex-rind** [comment]
_Why does one need to click the button anyway?_ To check if data was loaded as expected.

I think it is the workflow could be:
1. load data
2. immediately see the data (what "View Data" does now)
3. load another data OR start visualization (thus I would move both options into the grey bar)

**Comment by aiwo77** [comment]
Maybe even a step further in reducing clicks for the user:

1. load data
2. immediately start visualization (without clicking "start visualization")
3. dataset title is shown in header area (as discussed yesterday)
4. "view data" button next to dataset title (same functionality as now but from within the vis screen)
5. "load new data"/"close"/"x" button next to others that takes you to the data load screen

**Comment by NChristina** [comment]
load data -> data correct -> go to visualization (Load & Show)
if error stay at data import view 
view data vis view -> no button 

Sidebar -> Textfeld Save (Notebook) (save text)  - save file -> .txt
