### ISSUE TITLE
Implement "user review" from pretest

### ISSUE THREAD

**Issue by doomsayer2** [VALIDproject/netflower#151]
- Bug when first time loaded in header, with showing time labels
- Add Q or other präposition for time labels in features bar
- Save flows and logs files with timestamps
- Show overflowing tooltips at sparkline bar charts
- Move tooltip generally a bit away from mouse position

**Comment by alex-rind** [comment]
- “…” bei langem 1. Wort des Node Label
- im Connection Dialog die Spaltenüberschrift (hier "Paragraph") links von den checkboxen anzeigen
- Time Filter: verallg. Datumsformat (Methode aus Sparkline) verwenden
- Textboxen zu Slider zu klein Max. Zahl für source und target abgeschnitten
