### ISSUE TITLE
Priority from 4th pretest

### ISSUE THREAD

**Issue by alex-rind** [VALIDproject/netflower#153]
- [x] Clear All Filter BUG: die Min werte der Slider werden auf 0 gesetzt? macht nicht sinn, sollte auf den State geladen werden wie beim Öffnen. 
- [x] Texte beim Time Filter anpassen -> CN
- [x]  Suche: X - Button nur anzeigen, wenn die Userin nach Nodes sucht
- [x]  Data Loading View: Select File Button -> Design adaptieren
- [x]  Sparklines: Text wird abgeschnitten wenn die Sparklines knapp untereinander sind

**Comment by doomsayer2** [comment]
>  Suche: X - Button nur anzeigen, wenn die Userin nach Nodes sucht

I don't get whats the purpose here. You mean the clear of the search fields should only appear if you enter something? Thats unnecessary overload imo.

**Comment by NChristina** [comment]
>  Suche: X - Button nur anzeigen, wenn die Userin nach Nodes sucht 
Warum ein overload? Es gibt einfach den Button nicht -> erst wenn der User nach etwas sucht erscheint der Button.

**Comment by doomsayer2** [comment]
Why not leave it there... i mean why add further moving elements when it just can be there. Its unnecessary code overload i mean.
