### ISSUE TITLE
Export Data - include Tags

### ISSUE THREAD

**Issue by NChristina** [VALIDproject/netflower#191]
- [x] Tags should be seperated by "|" to add more tags to one node. 
- [x] Also save or export Tags this way.

**Comment by doomsayer2** [comment]
- Create 1 Radio buttons under "Export Data" for export with summarized values over time or seperate values over time
- Default is summarized values over time
- Exported csv should have First line with Meta data

**Comment by doomsayer2** [comment]
Name the Button "Export Visible Data"
