### ISSUE TITLE
Reupload sample files 

### ISSUE THREAD

**Issue by NChristina** [VALIDproject/netflower#194]

**Comment by doomsayer2** [comment]
Specify which files and what should be new. Also we should see what we keep and what we dont need.

**Comment by alex-rind** [comment]
* Simple_Data.csv reformated
* MTD  updated to 2018 Q2 data in new format plus Bundesland as a tag 
* Aid_Payments_OECD.csv works without reformat

**Comment by alex-rind** [comment]
* oecd_development_assistance.csv neues Datenset, evt. statt Aid_Payments_OECD.csv
* Asylum_Seekers_Data.csv reformated
* Farm_Subsidies_Data.csv works without reformat
